apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: observabilidade-fast-api
  annotations:
    github.com/project-slug: magnomatos822/observabilidade-fast-api
spec:
  type: other
  lifecycle: unknown
