version: "3.4"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  app-a:
    # build: ./fastapi_app/
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    container_name: app-a
    ports:
      - "8003:8000"
    depends_on:
      - otel-collector
      - loki
    environment:
      APP_NAME: "app-a"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        loki-pipeline-stages: |
          - multiline:
              firstline: '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}'
              max_wait_time: 3s
          - regex:
              expression: '^(?P<time>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2},d{3}) (?P<message>(?s:.*))$$'

  app-b:
    # build: ./fastapi_app/
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    container_name: app-b
    ports:
      - "8001:8000"
    depends_on:
      - otel-collector
      - loki
    environment:
      APP_NAME: "app-b"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        loki-pipeline-stages: |
          - multiline:
              firstline: '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}'
              max_wait_time: 3s
          - regex:
              expression: '^(?P<time>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2},d{3}) (?P<message>(?s:.*))$$'

  app-c:
    # build: ./fastapi_app/
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    container_name: app-c
    ports:
      - "8002:8000"
    depends_on:
      - otel-collector
      - loki
    environment:
      APP_NAME: "app-c"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        loki-pipeline-stages: |
          - multiline:
              firstline: '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}'
              max_wait_time: 3s
          - regex:
              expression: '^(?P<time>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2},d{3}) (?P<message>(?s:.*))$$'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - otel-collector
      - loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        loki-pipeline-stages: |
          - multiline:
              firstline: '^\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}'
              max_wait_time: 3s
          - regex:
              expression: '^(?P<time>\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{4}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}-\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2} \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{1,2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2}:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\d{2},d{3}) (?P<message>(?s:.*))$$'

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo/:/etc
    ports:
      - "14268"
      - "3200"
      - "9411"

  # k6-tracing:
  #   image: ghcr.io/grafana/xk6-client-tracing:latest
  #   container_name: k6-tracing
  #   environment:
  #     - ENDPOINT=otel-collector:4317
  #   restart: always
  #   depends_on:
  #     - otel-collector

  grafana:
    image: grafana/grafana-oss:11.2.2
    container_name: grafana
    volumes:
      - ./etc/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./etc/otel/:/etc/otel/  # Monta o diretório, não apenas o arquivo
    command: ["--config", "/etc/otel/config.yaml"]  # O caminho para o arquivo de configuração está correto

  # jaeger:
  #   image: jaegertracing/all-in-one:1.41
  #   ports:
  #     - "5775:5775"  # UDP
  #     - "6831:6831"  # UDP
  #     - "6832:6832"  # UDP
  #     - "5778:5778"  # HTTP
  #     - "16686:16686"  # UI
  #     - "14268:14268"  # Thrift HTTP
  #     - "14250:14250"  # Thrift

  