receivers:
  otlp:
    protocols:
      grpc:
      http:
    endpoint: 0.0.0.0:4317
exporters:
  loki:
    endpoint: http://localhost:3100/api/prom/push
    pipeline_stages:
      - multiline:
          firstline: '^\\d{4}-\\d{2}-\\d{2} \\d{1,2}:\\d{2}:\\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{1,2}:\\d{2}:\\d{2},d{3}) (?P<message>(?s:.*))$$'
  tempo:
    endpoint: http://localhost:4318
processors:
  batch:
    timeout: 1s
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - tempo
        - loki
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
        - loki
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - loki