receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  tempo:
    endpoint: "http://tempo:3200"

  jaeger:
    endpoint: "jaeger:16686" # Endereço do Jaeger
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [tempo, otlp, jaeger]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      exporters: [loki]
